const CREATED = 201;
const BAD_REQUEST = 400;
const AUTH_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const SERVER_ERROR = 500;
const DUBLICATION_ERROR = 11000;

module.exports = {
  CREATED,
  BAD_REQUEST,
  AUTH_ERROR,
  FORBIDDEN_ERROR,
  NOT_FOUND,
  CONFLICT_ERROR,
  SERVER_ERROR,
  DUBLICATION_ERROR,
};
